image: eclipse-temurin:17-jdk

stages:
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"


cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .m2/repository
    - .sonar/cache

.test-templete : &test-templete
  stage: test
  script:
    - apt update && apt install curl -y
    - ./mvnw -U clean $MAVEN_CLI_OPTS test verify sonar:sonar -Dgpg.skip=true
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -R $(pwd)

.deploy-template: &deploy-template
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y gnupg2
    - export GPG_TTY=$(tty)
    - echo "${GPG_PRI}" | gpg --batch --import
    
test:
  <<: *test-templete
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
    SONAR_USER_HOME: "/root/.sonar/${CI_PROJECT_NAME}"
  before_script:
    - mkdir -p ${SONAR_USER_HOME}
  except:
    changes:
      - "*.md"
  tags:
    - build

test-tags:
  <<: *test-templete
  only:
    - tags

deploy-snapshot:
  <<: *deploy-template
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/root/.m2/repository"
    SONAR_USER_HOME: "/root/.sonar/${CI_PROJECT_NAME}"
  script:
    - ./mvnw -U clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dmaven.test.skip=true -s settings.xml
  except:
    refs:
     - "/^*.release$/"
    changes:
      - "*.md"
  tags:
    - build
      
deploy-release :
  <<: *deploy-template
  script:
    - SNAPSHOT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version | grep "^[^\\[]" |grep -v Download)
    - RELEASE_VERSION=${SNAPSHOT_VERSION/-SNAPSHOT/}
#    - ./mvnw versions:set -DnewVersion=${RELEASE_VERSION}
#    - ./mvnw versions:set -DnewVersion=${RELEASE_VERSION} -pl opcal-cloud-commons-dependencies
#    - ./mvnw versions:set -DnewVersion=${RELEASE_VERSION} -pl opcal-cloud-starter-parent
    - ./ci/script/versions-set.sh ${RELEASE_VERSION}
    - ./mvnw -U clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dmaven.test.skip=true -s settings.xml
  only:
    - "/^*.release$/"


