image: openjdk:11-jdk-slim

stages:
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"


cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .m2/repository
    - .sonar/cache

.test-only : &test-only
  stage: test
  script:
    - ./mvnw clean $MAVEN_CLI_OPTS test -Dgpg.skip=true


.test-templete : &test-templete
  stage: test
  script:
    - apt update && apt install curl -y
    - ./mvnw clean $MAVEN_CLI_OPTS test verify sonar:sonar -Dgpg.skip=true
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov && ./codecov -t ${CODECOV_TOKEN}
    #    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
    
.deploy-template: &deploy-template
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y gnupg2
    - export GPG_TTY=$(tty)
    - echo "${GPG_PRI}" | gpg --batch --import
    
test:
  <<: *test-templete
  except:
    changes:
      - "*.md"

test-tags:
  <<: *test-templete
  only:
    - tags

test-temurin:
  <<: *test-only
  image: eclipse-temurin:11-jdk-focal
  except:
    changes:
      - "*.md"

test-tags-temurin:
  <<: *test-only
  image: eclipse-temurin:11-jdk-focal
  only:
    - tags
      
deploy-snapshot:
  <<: *deploy-template
  script:
    - ./mvnw clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dmaven.test.skip=true -s settings.xml
  except:
    refs:
     - "/^*.release$/"
    changes:
      - "*.md"

      
deploy-release :
  <<: *deploy-template
  script:
    - SNAPSHOT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version | grep "^[^\\[]" |grep -v Download)
    - RELEASE_VERSION=${SNAPSHOT_VERSION/-SNAPSHOT/}
    - ./mvnw versions:set -DnewVersion=${RELEASE_VERSION}
    - ./mvnw clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dmaven.test.skip=true -s settings.xml
  only:
    - "/^*.release$/"


