image: openjdk:11-jdk-slim

stages:
  - test
  - deploy


variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"


cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .m2/repository
    - .sonar/cache
    
.test-templete : &test-templete
  stage: test
  script:
    - ./mvnw clean $MAVEN_CLI_OPTS test verify sonar:sonar -Dgpg.skip=true
    - bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
    
.deploy-template: &deploy-template
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y gnupg2
    - export GPG_TTY=$(tty)
    - echo "${GPG_PRI}" | gpg --batch --import
    
test:
  <<: *test-templete
  except:
    changes:
      - "*.md"
      
test-tags:
  <<: *test-templete
  only:
    - tags
      
deploy-snapshot:
  <<: *deploy-template
  script:
    - ./mvnw clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dmaven.test.skip=true -s settings.xml
  except:
    refs:
     - "/^*.release$/"
    changes:
      - "*.md"

      
deploy-release :
  <<: *deploy-template
  script:
    - SNAPSHOT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version | grep "^[^\\[]" |grep -v Download)
    - RELEASE_VERSION=${SNAPSHOT_VERSION/-SNAPSHOT/}
    - ./mvnw clean $MAVEN_CLI_OPTS deploy -Dgpg.passphrase=${GPG_PASSPHRASE} -Dproject.version=${RELEASE_VERSION} -Dmaven.test.skip=true -s settings.xml
  only:
    - "/^*.release$/"


